[package]
name = "bonsai_genesis"
version = "0.0.1"
authors = ["xanxys@gmail.com"]

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http"
